############################
# 1. Differential input clock (200MHz)
############################
set_property PACKAGE_PIN AK17 [get_ports clk_p]
set_property PACKAGE_PIN AK16 [get_ports clk_n]
set_property IOSTANDARD LVDS [get_ports clk_p]
set_property IOSTANDARD LVDS [get_ports clk_n]

# Board input clock: 200MHz = 5.000ns
create_clock -name clk_in -period 5.000 [get_ports clk_p]

# Internal system clock generated by BUFGCE_DIV (/2): 100MHz = 10.000ns
create_generated_clock -name sys_clk -source [get_ports clk_p] -divide_by 2 [get_pins u_bufgce_div/O]

############################
# 2. UART pins
############################
set_property PACKAGE_PIN N27 [get_ports uart_rxd]
set_property PACKAGE_PIN K22 [get_ports uart_txd]

set_property IOSTANDARD LVCMOS18 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports uart_txd]
